name: Deploy Nodejs code on ExCloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Deploy on ExCloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 210.79.129.181
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            set -e

            echo "===== Loading NVM ====="

            export NVM_DIR="$HOME/.nvm"

            if [ -s "$NVM_DIR/nvm.sh" ]; then
              . "$NVM_DIR/nvm.sh"
            else
              echo "NVM not found!"
              exit 1
            fi

            nvm use 22

            echo "===== Node Environment ====="
            which node
            which npm
            node -v
            npm -v

            echo "===== Pulling the latest code ====="
            # CD /home/ubuntu/Next-Auth
            cd /home/ubuntu/Next-Auth

            # git pull
            git pull origin main

            npm install
            npm run build
            pm2 restart next-app --update-env || pm2 start npm --name "next-app" -- start
            pm2 save